Crass, nvamelichev merge
libkeepass/libkeepass pull request #2
Opened 2017-03-31 19:44 UTC by Evidlo

Merging contributions from @crass, and @nvamelichev.

Summary of changes

- unicode fixes
- python3 support
- twofish encryption support for KDB3 databases (see [here](http://keepass.info/help/base/security.html))
- lots and lots of small fixes and code cleanup

@pschmitt, @phpwutz Would you care to take a quick look and see if everything checks out?  The tests succeeded for both python2 and python3 and I also successfully ran the tests for pykeepass.

2017-04-01 15:55 UTC, pschmitt commented
Nice! This should be worth a new release.

2017-04-01 16:06 UTC, pschmitt requested changes

2017-04-01 16:06 UTC, pschmitt commented on setup.py
>      test_suite="tests"
Lines 27 and 14 are the same. This leads to the following error when trying to install using pip:
```Processing /home/pschmitt/dev/libkeepass
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-fOzaVK-build/setup.py", line 27
        test_suite="tests"
    SyntaxError: keyword argument repeated

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-fOzaVK-build/
```

2017-04-01 16:11 UTC, pschmitt approved these changes

2017-04-02 18:49 UTC, merged

2017-04-03 06:23 UTC, pschmitt commented
@phpwutz any objections against merging this?

2017-04-03 19:22 UTC, phpwutz commented
from a superficial inspection, no objections 👍