Add option to write to kdbx databases
libkeepass/libkeepass pull request #5
Opened 2017-07-28 18:29 UTC by wget

Sometimes, we need to write to kdbx file. This library doesn't allow this ability without having to declare yet another file descriptor, just to be able to write.

This patch adds the ability to reuse the existing file descriptor opened in `pykeepass`'s `open` context manager.

2017-07-28 19:58 UTC, Evidlo commented
I think a better solution might be something like this:

```
def open(filename, mode='rw', **credentials):
    """
    A contextmanager to open the KeePass file with `filename`. Use a `password`
    and/or `keyfile` named argument for decryption.
    
    Files are identified using their signature and a reader suitable for 
    the file format is intialized and returned.
    
    Note: `keyfile` is currently not supported for v3 KeePass files.
    """
    kdb = None
    try:
        with io.open(filename, mode) as stream:
            signature = common.read_signature(stream)
            cls = get_kdb_reader(signature)
            kdb = cls(stream, **credentials)
            yield kdb
            kdb.close()
    except:
        if kdb:
            kdb.close()
        raise

```

2017-07-28 22:17 UTC, wget commented
@Evidlo Ok done as well.

2017-07-28 23:25 UTC, Evidlo approved these changes

2017-07-30 05:07 UTC, Evidlo commented
The mode should actually be 'rb+' as per the [io documentation](https://docs.python.org/2/library/io.html#module-interface).  

Be sure to test your code before making a PR.  I'm partially at fault too for approving it before testing.

2017-07-30 07:56 UTC, pschmitt commented
+1 for `rb+`

2017-07-30 07:57 UTC, pschmitt requested changes
Please update that to `rb+`

2017-07-30 11:25 UTC, wget commented
@pschmitt Done.
@Evidlo Btw, I was using `r+b` in my previous PR and I tested it. But yes, I have to admit I haven't tested for `rw` nor `rb+` (only `r+b` has been tested).

2017-08-01 16:44 UTC, pschmitt commented
thanks!

2017-08-01 16:44 UTC, merged