Fix python3 detection
libkeepass/libkeepass pull request #6
Opened 2017-07-28 18:32 UTC by wget

The second condition shouldn't be checked when we are using Python 3, as that version of the language doesn't have the `file` type. Fix that.

2017-07-30 08:01 UTC, pschmitt commented
Thanks.

2017-07-30 08:09 UTC, pschmitt requested changes

2017-07-30 08:09 UTC, pschmitt commented on libkeepass/kdb4.py
> +        if not (isinstance(stream, io.IOBase)) or (not IS_PYTHON_3 and not isinstance(stream, file)):
`IS_PYTHON_3` is not imported.
And wouldn't it make sense to make use of the `_is_file()` function instead?

2017-07-30 08:10 UTC, pschmitt commented on libkeepass/kdb4.py
> +        if not (isinstance(stream, io.IOBase)) or (not IS_PYTHON_3 and not isinstance(stream, file)):
https://github.com/libkeepass/libkeepass/blob/master/libkeepass/common.py#L151

2017-07-30 11:21 UTC, wget commented on libkeepass/kdb4.py
> +        if not (isinstance(stream, io.IOBase)) or (not IS_PYTHON_3 and not isinstance(stream, file)):
@pschmitt Indeed, that's even better as this avoids code duplication. Btw, do you think we still need to support Python2? Scripts compatible with both versions become hard to maintain (from my young experience). :-/

2017-07-30 11:28 UTC, pschmitt commented on libkeepass/kdb4.py
> +        if not (isinstance(stream, io.IOBase)) or (not IS_PYTHON_3 and not isinstance(stream, file)):
We'll probably drop Python 2 support at some point. But this here is not place nor the time to discuss this.

2017-08-01 16:40 UTC, pschmitt commented
lgtm. Thanks.

2017-08-01 16:40 UTC, merged